### ISSUE TITLE
Version 1.0.2 gives 404 when updating password

### ISSUE THREAD

**Issue by wahidnory** [tuyennn/magento2-change-customer-password#6]
There's an error with the latest version of this release. Mainly with updating the password of the customer.
Magento returns a 404 and does not update the password.

### Preconditions (*)

1. Magento 2.4.2
2. Module version 1.0.2

### Steps to reproduce (*)

2. go to customer
3. type new password
4. update the password

### Expected result (*)

Password should be updated and redirected to customer page

### Actual result (*)

Magento throws 404 with page not found error

### Possible fix
This is because of the Controller named `ChangeAction` and it's being redirected to `/admin/customer/password/change/`

To fix this it would be required to rename the controller to Change, or to redirect to changeaction, depending on how you prefer to solve this.

Thank you in advance.

**Comment by tuyennn** [comment]
Thanks @wahidnory for the report
The [tag](https://github.com/tuyennn/magento2-change-customer-password/releases/tag/v1.0.2)  was updated since I don't want to release 1 more time,
Please update your hash on composer.lock whether you installed v1.0.2 already
